# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sneaky List â€“ A small CSS experiment
email: danielfosco@gmail.com
description: A small CSS experiment
baseurl: "/sneaky-list" # the subpath of your site, e.g. /blog
url: "http://danielfos.co" # the base hostname & protocol for your site
twitter_username: dfosco
github_username:  dfosco

# Build settings
markdown: kramdown

# Pretty URL
permalink: "posts/:title"

# Custom categories
categories: [navbar]

sass:
    style: :compressed
